"use strict";
var http = require('http')
    , fs = require('fs')
    , crypto = require('crypto')
    , moment = require('moment')
    , Sequence = require('futures').sequence
    , Promise = require('future')
    , exec = require("child_process").exec;

const CryptoJS = require("crypto-js")

const isDevelopment = process.env.NODE_ENV !== 'production'

class decrypt {
    // Stores name of outguess library.
    _outguess = '';

    // platform need to be passed
    constructor(platform) {
        // lets support 3 platforms only
        // binary will be provided by app for mac and windows
        // Assumption - other os will have outguess installed
        if (platform === 'WINDOWS') {
            this._outguess = isDevelopment ? './resources/bin/windows/outguess.exe' : process.resourcesPath + '/bin/windows/outguess.exe'
        } else if(platform === 'MAC') {
            this._outguess = isDevelopment ? './resources/bin/mac/outguess' : process.resourcesPath + '/bin/mac/outguess'
        } else {
            // Assumption - outguess is installend
            this._outguess = 'outguess'
        }
    }

    get outguess() {
        return this._outguess;
    }

    decryption(image) {
        // this variable is generated by ./passman.js
        const filename = 'public.keyfile'
        const public_key_file = `${process.env.PASSMAN_USER_DIR}${filename}`

        // lets read file generated while sign up
        // this will extract 32 character key
        let pub_key

        var promise = Promise()

        fs.access(public_key_file, fs.constants.F_OK, (err) => {
            if ( err ) {
                // file not exists.
                promise.fulfill(true, 'Security key does not exists.')

                next()
            } else {
                // file exists, lets read.
                let contents = fs.readFileSync(public_key_file)

                contents = Buffer.from(contents, 'base64').toString()

                // 256-bit Key - 32 length string
                // extracted from pubkey file
                const ENCRYPTION_KEY = CryptoJS.TripleDES.decrypt(contents, process.env.PASSMAN_PUBLIC_SECURITY_KEY).toString(CryptoJS.enc.Utf8)

                let user_email = process.env.PASSMAN_APP_USER_EMAIL

                // lets read user password
                // password and key will be used for cipher encryption
                const db = require('./db')

                try {
                    let main = this
                    // lets get user password
                    db.serialize(function() {
                        db.each(`SELECT * from user where email="${user_email}";`, function(err, row) {
                            const password = CryptoJS.Rabbit.decrypt(row.password, process.env.PASSMAN_PASSWORD_KEY).toString(CryptoJS.enc.Utf8)

                            // decryption takes place here.
                            Sequence()
                                .then(function(next) {
                                    // console.log('--Testing DECRYPT--')

                                    main.perform(ENCRYPTION_KEY, password, image)
                                        .when(function(err, internalData) {
                                            if (err) {
                                                console.log(err)
                                            }
                                            // console.log('[OUTPUT] Decrypted message: ' + data + '\n')

                                            promise.fulfill(undefined, internalData)

                                            next()
                                        })
                                })
                        })
                    })
                } catch ( error ) {
                    // error
                    promise.fulfill(true, error.toString())

                    next()
                }
            }
        })

        return promise
    }

    perform(ENCRYPTION_KEY, PASSWORD, IMGFILE) {
        let main = this
        ENCRYPTION_KEY = Buffer.from(ENCRYPTION_KEY)

        const algorightm = 'aes-256-ctr'

        var promise = Promise()

        new Sequence()
            .then(function(next) {
                var filename = process.env.PASSMAN_USER_DIR + moment().valueOf().toString(36).toString('utf8') + '.txt'

                var cmd = main._outguess + " -k \'" + PASSWORD + "\' -r " + IMGFILE + " " + filename
                exec(cmd , function(err, stdout, stderr) {
                    next(filename)
                })
            })


            .then(function(next, filename) {
                fs.readFile(filename, function(err, data) {
                    next(data, filename)
                });
            })


            .then(function(next, data, filename) {
                let decrypted = ''
                try {
                    //if (data.isString('utf8')) {
                        //console.log('is string!');


                    //} else {
                        //console.log('not string!');

                    //}
                    let textParts = data.toString().split(':')
                    let iv = Buffer.from(textParts.shift(), 'hex')
                    let encryptedText = Buffer.from(textParts.join(':'), 'hex')

                    let decipher = crypto.createDecipheriv(algorightm, Buffer.from(ENCRYPTION_KEY, 'hex'), iv)
                    decrypted = decipher.update(encryptedText)
                    decrypted = Buffer.concat([decrypted, decipher.final()])

                    decrypted = decrypted.toString()

                    if (decrypted === '') {
                        promise.fulfill(undefined, decrypted)

                    } else {
                        promise.fulfill(undefined, decrypted)

                    }
                    next(filename)
                } catch (ex) {
                    promise.fulfill(true, ex.toString())
                    next(filename)
                }
            })

            .then(function(next, filename) {
                fs.unlink(filename, function() {
                    next()
                })
            });

        return promise
    }
}

module.exports = decrypt